CREATE TABLE bills (
  id BIGSERIAL UNIQUE PRIMARY KEY NOT NULL,
  value INT NOT NULL,
  currency VARCHAR(255) NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE users_bills (
  id BIGSERIAL UNIQUE PRIMARY KEY NOT NULL,
  user_id BIGINT REFERENCES users ON DELETE CASCADE,
  bill_id BIGINT REFERENCES bills ON DELETE CASCADE UNIQUE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);