CREATE TABLE bills (
  id BIGSERIAL UNIQUE PRIMARY KEY NOT NULL,
  user_id BIGINT REFERENCES users ON DELETE CASCADE,
  family_id BIGINT REFERENCES users ON DELETE CASCADE,
  value INT NOT NULL,
  currency VARCHAR(255) NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);