CREATE TABLE incomes (
  id BIGSERIAL UNIQUE PRIMARY KEY NOT NULL,
  value INT NOT NULL,
  currency VARCHAR(255) NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE incomes_users (
  id BIGSERIAL UNIQUE PRIMARY KEY NOT NULL,
  user_id BIGINT REFERENCES users ON DELETE CASCADE NOT NULL,
  income_id BIGINT REFERENCES incomes ON DELETE CASCADE NOT NULL UNIQUE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE incomes_families (
  id BIGSERIAL UNIQUE PRIMARY KEY NOT NULL,
  family_id BIGINT REFERENCES families ON DELETE CASCADE NOT NULL,
  income_id BIGINT REFERENCES incomes ON DELETE CASCADE NOT NULL UNIQUE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);