CREATE TABLE bill_weekly_due_dates (
  id BIGSERIAL UNIQUE PRIMARY KEY NOT NULL,
  bill_id BIGINT REFERENCES bills ON DELETE CASCADE NOT NULL,
  week_day VARCHAR(255) NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE bill_month_due_dates (
  id BIGSERIAL UNIQUE PRIMARY KEY NOT NULL,
  bill_id BIGINT REFERENCES bills ON DELETE CASCADE NOT NULL,
  day INT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE bill_week_day_month_due_dates (
  id            BIGSERIAL UNIQUE PRIMARY KEY NOT NULL,
  bill_id       BIGINT REFERENCES bills ON DELETE CASCADE NOT NULL,
  week_day      VARCHAR(255) NOT NULL,
  sequence_day  INT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE bill_year_due_dates (
  id BIGSERIAL UNIQUE PRIMARY KEY NOT NULL,
  bill_id BIGINT REFERENCES bills ON DELETE CASCADE NOT NULL,
  month VARCHAR(255) NOT NULL,
  day INT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);