x-db-connect: &db-connect
  DB_USER: db_user
  DB_PASS: db_pass
  DB_HOST: db
  DB_NAME: db_name?sslmode=disable
  DB_PORT: 5432
services:
  app:
    image: golang:1.23
    working_dir: /usr/src/app
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - .:/usr/src/app
      - go_pkg:/go/pkg
    environment:
      <<: *db-connect
      GOCACHE: /usr/src/app/.cache/go-build
    depends_on:
      - db
      - migrations
  migrations:
    image: guilhermewebdev/migrator:slim-v0.3
    working_dir: /usr/src/app
    user: ${UID:-1000}:${GID:-1000}
    command: migrate latest
    volumes:
      - .:/usr/src/app
    environment:
      <<: *db-connect
    depends_on:
      - db
  db:
    image: postgres:17
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
      POSTGRES_DB: db_name
volumes:
  go_pkg:
  db_data: