CREATE TABLE plans (
  id BIGSERIAL UNIQUE PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  value INT NOT NULL,
  duration INT NOT NULL,
  active BOOLEAN NOT NULL,
  currency VARCHAR(255) NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE subscriptions (
  id BIGSERIAL UNIQUE PRIMARY KEY NOT NULL,
  plan_id BIGINT REFERENCES plans ON DELETE CASCADE NOT NULL,
  family_id BIGINT REFERENCES families ON DELETE CASCADE NOT NULL,
  due_date TIMESTAMPTZ NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

