CREATE TABLE families (
  id BIGSERIAL UNIQUE PRIMARY KEY NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE users_families (
  id BIGSERIAL UNIQUE PRIMARY KEY NOT NULL,
  user_id BIGINT REFERENCES users ON DELETE CASCADE NOT NULL,
  family_id BIGINT REFERENCES families ON DELETE CASCADE NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);