CREATE TABLE families_bills (
  id BIGSERIAL UNIQUE PRIMARY KEY NOT NULL,
  family_id BIGINT REFERENCES families ON DELETE CASCADE,
  bill_id BIGINT REFERENCES bills ON DELETE CASCADE UNIQUE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);