CREATE TABLE goals (
  id BIGSERIAL UNIQUE PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  value INT NOT NULL,
  currency VARCHAR(255) NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE users_goals (
  id BIGSERIAL UNIQUE PRIMARY KEY NOT NULL,
  user_id BIGINT REFERENCES users ON DELETE CASCADE,
  goal_id BIGINT REFERENCES goals ON DELETE CASCADE UNIQUE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE families_goals (
  id BIGSERIAL UNIQUE PRIMARY KEY NOT NULL,
  family_id BIGINT REFERENCES families ON DELETE CASCADE,
  goal_id BIGINT REFERENCES goals ON DELETE CASCADE UNIQUE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);