CREATE TABLE family_bill_categories (
  id BIGSERIAL UNIQUE PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  family_id BIGINT REFERENCES families ON DELETE CASCADE NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE bills
  ADD category_id BIGINT REFERENCES family_bill_categories ON DELETE CASCADE NOT NULL;